export enum AppointmentStatus {
    PENDING = 'PENDING',
    REPROGRAMMED = 'REPROGRAMMED',
    PENDING_OWNER = 'PENDING_OWNER',
    CONFIRMED = 'CONFIRMED',
    CANCELED = 'CANCELED',
    PENDING_CLIENT = 'PENDING_CLIENT',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
}
