name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - uses: actions/checkout@v4

    # 2. Iniciar sesión en el registro de contenedores
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3. Construir la imagen Docker
    - name: Build the Docker image
      run: docker build . --file dockerfile.prod --tag ghcr.io/${{ github.repository }}.dev:latest

    # 4. Publicar la imagen Docker en el registro
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}.dev:latest

    # 5. Conectarse al servidor y hacer el despliegue
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.DEV_EC2_HOST }}
        timeout: 120s
        proxy_timeout: 120s
        username: ${{ secrets.DEV_EC2_USER }}
        key: ${{ secrets.DEV_EC2_SSH_KEY }}
        script: |
          cd /home/admin/plugin-launcher
          git pull
          docker compose -f docker-compose.dev.yml down backend
          docker images | grep 'ghcr.io/${{ github.repository }}.dev' | awk '{print $3}' | xargs docker rmi -f
          docker compose -f docker-compose.dev.yml pull backend
          docker compose -f docker-compose.dev.yml up backend -d
