name: Docker Image CI prod

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - uses: actions/checkout@v4

    # 2. Iniciar sesión en el registro de contenedores
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3. Construir la imagen Docker
    - name: Build the Docker image
      run: docker build . --file dockerfile.prod --tag ghcr.io/${{ github.repository }}:latest

    # 4. Publicar la imagen Docker en el registro
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest

    # 5. Conectarse al servidor y hacer el despliegue
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/admin/plugin-launcher
          git pull
          docker compose pull backend
          docker compose down backend
          docker compose up backend -d
